### ISSUE TITLE
Fix Indentation

### ISSUE THREAD

**Issue by jcsawyer123** [rhul-compsoc/royal-hackaway#1]
The current indentation/styling is disgusting.

Go through the whole code and make it consistent

**Comment by ab-gh** [comment]
[branch](https://github.com/rhul-compsoc/royal-hackaway/tree/1-fix-indentation)

**Comment by 7coil** [comment]
What should the indentation be (for people working on other branches like #3 #5 and #7?)

**Comment by 7coil** [comment]
The ReactJS branch is super _stylish_ and _formatted_, and shall continue to be every time someone runs `yarn format`

Unsure what to do with `master`.
